### ISSUE TITLE
clarify how read is supposed to work

### ISSUE THREAD

**Issue by chessai** [andrewthad/rotera#12]
for example, in the repl:

```
>>> :batch 2
>>> :push msg1
>>> :push msg2
>>> :read -- returns nothing
>>> :read-batch 2 -- returns nothing
```

both `:read` and `:read-batch 2` return nothing here. do i misunderstand something?

**Comment by andrewthad** [comment]
The current logic for both `read` and `read-batch` includes:

```
      R.ping conn currentQueue >>= \case
        Left err -> do
          putStr $ errPing err
        Right R.Status{next} -> do
          R.read conn currentQueue next b >>= \case
```

This means that both will attempt a read starting at the next unassigned message id. This will almost always return an empty set of messages. For the starting message id, what you actually want is `next - b`.

Also, I'm not sure that having a `read-batch` command makes a whole lot of sense. Certainly a `read-at` command, where the user picks out a message id to start at, makes sense. Or perhaps they could be consolidated by `read` accepting an optional argument. I'm not sure if `repline` likes optional arguments though.

**Comment by chessai** [comment]
repline doesn't care, it leaves all parsing up to you
