### ISSUE TITLE
what's in a rot?

### ISSUE THREAD

**Issue by chessai** [andrewthad/rotera#3]
are there any special requirements on rot files? anything that needs to be in them? i created a systemd service that runs rotera. it's written in nix. you can find it here: https://github.com/chessai/nixos-configs/blob/master/services/rotera.nix

rotera's home directory is set as /var/lib/rotera, and this is also where the user's specified .rot files are created. however, rotera always fails with "Rotera.open: magic header was invalid", which indicates to me that something is wrong with those files.

**Comment by chessai** [comment]
note that currently the nix services just calls `touch ${r}.rot`, for all r in the list of queues you want. nothing else.

**Comment by andrewthad** [comment]
The format of these files is not documented anywhere yet. The best way to create a correct one is to run the `rotera` application that comes with the library.  The first 4 kB are special.  They are a header block, similar in spirit to what LMDB does.  Then, there is the data section which contains the raw messages all butted up against one another. Last is the message offsets section.

**Comment by chessai** [comment]
Okay, i'll have it do that.

**Comment by chessai** [comment]
Why does it write the file to 'rotera.bin'?

**Comment by chessai** [comment]
Why not take a filepath? Also, shouldn't it be a .rot extension?

**Comment by andrewthad** [comment]
It uses `rotera.bin` because I wrote that code much earlier on. It should use a filename something with a `.rot` extension. And the filename should be configurable with a flag. I've gotten by in my simple testing so far by just renaming the file by hand and using it with `rotera-server`.

**Comment by andrewthad** [comment]
Also, I should add that I love that the name of this issue is "what's in a rot?"

**Comment by chessai** [comment]
i now have a working rotera systemd service configured with nix

**Comment by chessai** [comment]
https://github.com/chessai/nixos-configs/blob/master/services/rotera.nix

**Comment by chessai** [comment]
i made some changes to rotera, i'll need to pr those
