### ISSUE TITLE
repl ideas

### ISSUE THREAD

**Issue by chessai** [andrewthad/rotera#8]
commands:
`:queue <u32>` : update queue that we're pointing to
`:print-ids {on|off}`: whether or not to print message ids
`:batch <u32>` : update default number of messsages to read
`:read` : read `batch` number of messages
`:read-batch <u32>`: read the given number of messages
`:push <msg>`: push the message to the current queue.

no stream, as that could just block up the repl for a long time. push should just always commit from the repl.

**Comment by andrewthad** [comment]
I like this set of commands.

**Comment by chessai** [comment]
we also want:

`:ping` -- ping rotera-server and return the most recent commit.
`:current` -- show current settings.

**Comment by chessai** [comment]
this is all implemented, but pushing to rotera-server is consistently causing a segfault for some reason.

**Comment by andrewthad** [comment]
I am able to reproduce the segfault. This only happens when using `rotera-repl`, not when using `rotera-client`. This means that the server is not doing some error checking that it should be doing.

**Comment by chessai** [comment]
okay. makes sense.

**Comment by chessai** [comment]
repl is done
